# Generated by Django 2.2.28 on 2023-11-28 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0012_product_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('category', '-created')},
        ),
    ]
